
name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake bison re2c libgmp-dev libmpfr-dev libboost-all-dev gringo clasp python3-pip

      - name: Install networkx
        run: |
          pip install networkx
          pip install clingo

      - name: Run build
        run: |
          chmod +x build.sh
          ./build.sh
          
      - name: Sample Hashcount run
        run: |
          cd scripts
          python run_hashcount.py -i mccmc2021_track1_058.cnf

      - name: Sample Hashcount run
        run: |
          cd scripts
          python run_hashcount.py -i minimal_vote.cnf

      - name: Sample ProjEnum Run
        run: |
          cd scripts
          python run_projenum.py -i mccmc2021_track1_058.cnf

      - name: Sample ProjEnum Run
        run: |
          cd scripts
          python run_projenum.py -i minimal_vote.cnf

      - name: Sample MinLB Run
        run: |
          cd scripts
          python run_minlb.py -i mccmc2021_track1_058.cnf

      - name: Sample MinLB Run
        run: |
          cd scripts
          python run_minlb.py -i minimal_vote.cnf